### ISSUE TITLE
Publishing a version on Pypi

### ISSUE THREAD

**Issue by belug23** [mklein0/sqlalchemy-zipkin#3]
Hi, I was wondering if you would accept to publish the latest code on pypi to make it easier to deploy.

Thanks.

**Comment by mklein0** [comment]
I can do that. I am wondering if I should rename the package though with zipkin being the primary as this is a driver for it.

`zipkin-sqlalchemy`

**Comment by mklein0** [comment]
At the same time, it instruments SQLAlchemy for zipkin, so the current name works as well.

**Comment by belug23** [comment]
The other packages I use are named `<package>-zipkin` so I would keep the name like that.

**Comment by mklein0** [comment]
I have generated a new release with the recent changes and pushed it to PyPi:
- https://pypi.org/project/SQLAlchemy-Zipkin/0.2.0/

**Comment by belug23** [comment]
Thanks I'm gonna test this tomorrow!
